### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by MartinSVK12** [MartinSVK12/signalindustries#14]
```
java.lang.NullPointerException: Cannot read field "tier" because the return value of "sunsetsatellite.signalindustries.inventories.machines.TileEntityCrystalCutter.getBlockType()" is null
    at sunsetsatellite.signalindustries.gui.GuiCrystalCutter.drawGuiContainerBackgroundLayer(GuiCrystalCutter.java:86)
    at net.minecraft.client.gui.GuiContainer.drawScreen(GuiContainer.java:75)
    at sunsetsatellite.catalyst.fluids.impl.GuiFluid.drawScreen(GuiFluid.java:33)
    at sunsetsatellite.signalindustries.gui.GuiCrystalCutter.drawScreen(GuiCrystalCutter.java:38)
    at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:576)
    at net.minecraft.client.Minecraft.run(Minecraft.java:842)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MartinSVK12** [comment]
Fixed by 5b0f56f.
