### ISSUE TITLE
Crash upon hitting/breaking conduits

### ISSUE THREAD

**Issue by GooseOnoob** [MartinSVK12/signalindustries#20]
### Error message
```
Minecraft ran into an unexpected problem!

To prevent more problems, the current game has quit, but you can try to keep playing.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 11/24/24 9:59 AM

Minecraft: Better than Adventure! 7.2
OS: Windows 11 (amd64) version 10.0
Java: 1.8.0_412, Temurin
VM: OpenJDK 64-Bit Server VM (mixed mode), Temurin
LWJGL: 2.9.4
OpenGL: AMD Radeon RX 6600 version 4.6.0 Compatibility Profile Context 24.7.1.240711, ATI Technologies Inc.

java.lang.NullPointerException
    at org.useless.dragonfly.model.block.BlockModelDragonFly.getParticleTexture(BlockModelDragonFly.java:211)
    at sunsetsatellite.catalyst.multipart.block.model.BlockModelMultipart.getParticleTexture(BlockModelMultipart.java:59)
    at net.minecraft.client.entity.fx.EntityDiggingFX.<init>(EntityDiggingFX.java:24)
    at net.minecraft.client.render.EffectRenderer.addBlockHitEffects(EffectRenderer.java:201)
    at net.minecraft.client.player.controller.PlayerController.continueDestroyBlock(PlayerController.java:104)
    at net.minecraft.client.Minecraft.mineBlocks(Minecraft.java:1084)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1505)
    at net.minecraft.client.Minecraft.run(Minecraft.java:841)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by MartinSVK12** [comment]
This is an issue with Catalyst, but anyways, it will be fixed in the next update.
